import React from 'react'
import Footer from '../../share/Footer'
import Navbar from '../../share/Navbar';
import Head from 'next/head';
export default function Layout({children , title}) {
  return (
    <div> 
        <header>
        <Head>
        <title>{title ? title +  "-Empoly App" : "Empoly App"} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
        </header>
        <main>
        {children}
        </main>
        <footer>
      <Footer/>
        </footer>
    </div>
  )
}
